<!-- JAVASCRIPT  FILES ========================================= -->
<script src="{{asset('front/js/jquery-3.6.0.min.js')}}"></script><!-- JQUERY.MIN JS -->
<script src="{{asset('front/js/popper.min.js')}}"></script><!-- POPPER.MIN JS -->
<script src="{{asset('front/js/bootstrap.min.js')}}"></script><!-- BOOTSTRAP.MIN JS -->
<script src="{{asset('front/js/bootstrap-select.min.js')}}"></script><!-- BOOTSTRAP SELECT -->
<script src="{{asset('front/js/jquery.bootstrap-touchspin.js')}}"></script><!-- FORM JS -->
<script src="{{asset('front/js/magnific-popup.min.js')}}"></script><!-- MAGNIFIC-POPUP JS -->
<script src="{{asset('front/js/waypoints.min.js')}}"></script><!-- WAYPOINTS JS -->
<script src="{{asset('front/js/counterup.min.js')}}"></script><!-- COUNTERUP JS -->
<script src="{{asset('front/js/waypoints-sticky.min.js')}}"></script><!-- STICKY HEADER -->
<script src="{{asset('front/js/isotope.pkgd.min.js')}}"></script><!-- MASONRY  -->
<script src="{{asset('front/js/owl.carousel.min.js')}}"></script><!-- OWL  SLIDER  -->
<script src="{{asset('front/js/slick.min.js')}}"></script><!-- OWL  SLIDER  -->
<script src="{{asset('front/js/theia-sticky-sidebar.js')}}"></script><!-- STICKY SIDEBAR  -->
<script src="{{asset('front/js/m-custom-scrollbar.min.js')}}"></script><!-- my account left panel scroller -->
<script src="{{asset('front/js/dropzone.js')}}"></script><!-- Images upload -->
<script src="{{asset('front/js/bootstrap4-toggle.min.js')}}"></script>
<script src="{{asset('front/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('front/js/dataTables.bootstrap4.min.js')}}"></script>
<script src="{{asset('front/js/custom.js')}}"></script><!-- CUSTOM FUCTIONS  -->
<script src="{{asset('front/js/lc_lightbox.lite.js')}}"></script><!-- IMAGE POPUP -->
<script src="{{asset('front/js/bootstrap-slider.min.js')}}"></script><!-- Form js -->
